### ISSUE TITLE
Up to date?

### ISSUE THREAD

**Issue by PeteMac88** [platzhersh/graphql-hive-helm#1]
Hey there, first of all, thanks for providing this helm chart. Is this chart still up to date?  I saw comments from you on Reddit and in github issues regarding the deployment of hive to k8s. Is this the chart you working with in your organization and is the chart providing all the features of the docker-compose deployment?

**Comment by platzhersh** [comment]
Hey there @PeteMac88 

Yes this is the anonymised version of the chart we came up with. However I havent pushed all the latest changes on here.
I can look into it again next week.
But yes, it should provide all the features of the docker-compose file.

**Comment by PeteMac88** [comment]
@platzhersh That would be awesome and a huge help. In case you need help with something I would help but I had the feeling that this repo was not up to date.

**Comment by platzhersh** [comment]
@PeteMac88 I just updated the repo. Let me know if you have any issues or feedback
